controller_list:
  - name: fake_FR_ik_controller
    joints:
      - FRS_joint
      - FRL_joint
      - FRF_joint
  - name: fake_FL_ik_controller
    joints:
      - FLS_joint
      - FLL_joint
      - FLF_joint
  - name: fake_RR_ik_controller
    joints:
      - RRS_joint
      - RRL_joint
      - RRF_joint
  - name: fake_RL_ik_controller
    joints:
      - RLS_joint
      - RLL_joint
      - RLF_joint
initial:  # Define initial robot poses.
  - group: FR_ik
    pose: walk_pose
  - group: FL_ik
    pose: walk_pose
  - group: RR_ik
    pose: walk_pose
  - group: RL_ik
    pose: walk_pose